# Generated by Django 2.2 on 2022-05-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20220526_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='prodt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products'),
        ),
    ]
